spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/os_works?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: sna326411
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
      hibernate:
        type: trace