spring:
  datasource:
#    url: jdbc:postgresql://<Ip Da Maquina>:<Porta>/<Nome Do Banco De Dados>?useTimezone=true&serverTimezone=UTC&useLegacyDate
    url: jdbc:postgresql://localhost:5432/os_works?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres # Usuario
    password: sna326411 # Senha
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


logging:
  level:
    org:
      hibernate:
        type: trace